/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccine;

import javax.swing.JOptionPane;
import vaccine.Class.DataIO;

/**
 *
 * @author user
 */
public class AdminUpdateDose extends javax.swing.JFrame {

   /**
    * Creates new form AdminUpdateDose
    */
   public AdminUpdateDose() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel10 = new javax.swing.JLabel();
      btnBack2 = new javax.swing.JButton();
      txtIC = new javax.swing.JTextField();
      txtName = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      btnDose1 = new javax.swing.JButton();
      btnDose2 = new javax.swing.JButton();
      jLabel21 = new javax.swing.JLabel();
      chbDose1 = new javax.swing.JCheckBox();
      chbDose2 = new javax.swing.JCheckBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);

      jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel10.setText("Update Dose Status");
      jLabel10.setToolTipText("");
      jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      btnBack2.setText("Back ➤");
      btnBack2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBack2ActionPerformed(evt);
         }
      });

      txtIC.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            txtICFocusLost(evt);
         }
      });

      txtName.setEnabled(false);

      jLabel11.setText("IC No");

      jLabel20.setText("Recipient Name");

      btnDose1.setText("Completed Dose 1");
      btnDose1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDose1ActionPerformed(evt);
         }
      });

      btnDose2.setText("Completed Dose 2");
      btnDose2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDose2ActionPerformed(evt);
         }
      });

      jLabel21.setText("Current Dose");

      chbDose1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      chbDose1.setForeground(new java.awt.Color(0, 0, 0));
      chbDose1.setText("Dose 1 Completed");
      chbDose1.setEnabled(false);

      chbDose2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
      chbDose2.setForeground(new java.awt.Color(0, 0, 0));
      chbDose2.setText("Dose 2 Completed");
      chbDose2.setEnabled(false);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(43, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addContainerGap())
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                     .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(107, 107, 107)))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(txtIC, javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(chbDose1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(chbDose2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(txtName))))
         .addGroup(layout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(btnDose1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(57, 57, 57)
            .addComponent(btnDose2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(btnBack2)
            .addGap(29, 29, 29)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel11))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel21)
               .addComponent(chbDose1)
               .addComponent(chbDose2))
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnDose2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnDose1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(40, Short.MAX_VALUE))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
      AdminMain a = new AdminMain();
      a.setVisible(true);
      this.dispose();
   }//GEN-LAST:event_btnBack2ActionPerformed

   private void txtICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtICFocusLost
      if (!txtIC.getText().isBlank()) {
         Vaccine.app = DataIO.checkAppointment(txtIC.getText().trim());
         if (Vaccine.app == null) {
            txtName.setText("");
            JOptionPane.showMessageDialog(txtIC, "This user does not have an appointment");
         } else {
            txtIC.setText(Vaccine.app.getPerson().getIcno());
            txtName.setText(Vaccine.app.getPerson().getName());
            if (Vaccine.app.isDose1()) {
               chbDose1.setSelected(true);
               btnDose1.setEnabled(false);
            }
            if (!Vaccine.app.isDose1() && !Vaccine.app.isDose2()) {
               btnDose2.setEnabled(false);
               chbDose1.setSelected(false);
               chbDose2.setSelected(false);

            }
            if (Vaccine.app.isDose2()) {
               chbDose2.setSelected(true);
               btnDose2.setEnabled(false);

            }
         }
      }
   }//GEN-LAST:event_txtICFocusLost

   private void btnDose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDose1ActionPerformed
      int confirm = JOptionPane.showConfirmDialog(this, "1st Dose Received?", "Update Dose 1?", JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
         if (!txtIC.getText().isBlank()) {
            Vaccine.app = DataIO.checkAppointment(txtIC.getText().trim());
            if (Vaccine.app.isDose1()) {
               JOptionPane.showMessageDialog(btnDose1, "User already has completed their 1st dose");
            } else if (Vaccine.app.isDose2()) {
               JOptionPane.showMessageDialog(btnDose1, "User is already fully vaccinated");
            } else {
               chbDose1.setSelected(true);
               btnDose1.setEnabled(false);
               btnDose2.setEnabled(true);
               Vaccine.app.setDose1(true);
               DataIO.write();
            }
         } else {
            JOptionPane.showMessageDialog(btnDose1, "Please fill in the IC field");
         }
      }
   }//GEN-LAST:event_btnDose1ActionPerformed

   private void btnDose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDose2ActionPerformed
      int confirm = JOptionPane.showConfirmDialog(this, "2nd Dose Received?", "Update Dose 2?", JOptionPane.YES_NO_OPTION);
      if (confirm == JOptionPane.YES_OPTION) {
         if (!txtIC.getText().isBlank()) {
            Vaccine.app = DataIO.checkAppointment(txtIC.getText().trim());
            if (Vaccine.app.isDose1()) {
               chbDose2.setSelected(true);
               btnDose2.setEnabled(false);
               Vaccine.app.setDose2(true);
               DataIO.write();
            } else {
               JOptionPane.showMessageDialog(btnDose2, "Please complete the 1st dose before updating this button");
            }
         } else {
            JOptionPane.showMessageDialog(btnDose2, "Please fill in the IC field");
         }
      }
   }//GEN-LAST:event_btnDose2ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdminUpdateDose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdminUpdateDose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdminUpdateDose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdminUpdateDose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new AdminUpdateDose().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnBack;
   private javax.swing.JButton btnBack1;
   private javax.swing.JButton btnBack2;
   private javax.swing.JButton btnDose1;
   private javax.swing.JButton btnDose2;
   private javax.swing.JCheckBox chbDose1;
   private javax.swing.JCheckBox chbDose2;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JTextField txtIC;
   private javax.swing.JTextField txtName;
   // End of variables declaration//GEN-END:variables
}
