/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccine;

import javax.swing.table.DefaultTableModel;
import vaccine.Class.DataIO;

/**
 *
 * @author User
 */
public class AdminPeopleManagement extends javax.swing.JFrame {

   /**
    * Creates new form Admin_Profile
    */
   public AdminPeopleManagement() {
      initComponents();
      DataIO.read();
      DefaultTableModel model = (DefaultTableModel) tblPeople.getModel();
      model.setRowCount(0);
      for (int i = 0; i < DataIO.allPeople.size(); i++) {
         String icno = DataIO.allPeople.get(i).getIcno();
         String name = DataIO.allPeople.get(i).getName();
         String password = DataIO.allPeople.get(i).getPassword();
         String contact = DataIO.allPeople.get(i).getPhone();
         String citizen = String.valueOf(DataIO.allPeople.get(i).isCitizen());
         String array[] = {icno, name, password, contact, citizen};
         model.addRow(array);
      }
      tblPeople.getColumnModel().getColumn(2).setMinWidth(0);
      tblPeople.getColumnModel().getColumn(2).setMaxWidth(0);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      tblPeople = new javax.swing.JTable();
      txtSearch = new javax.swing.JTextField();
      btnRefresh = new javax.swing.JButton();
      jLabel6 = new javax.swing.JLabel();
      chkCitizen = new javax.swing.JCheckBox();
      txtName = new javax.swing.JTextField();
      txtIC = new javax.swing.JTextField();
      txtContact = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      btnRegister = new javax.swing.JButton();
      btnUpdate = new javax.swing.JButton();
      btnClear = new javax.swing.JButton();
      btnDelete = new javax.swing.JButton();
      jLabel7 = new javax.swing.JLabel();
      txtPassword = new javax.swing.JPasswordField();
      chkPassword = new javax.swing.JCheckBox();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setResizable(false);

      tblPeople.setAutoCreateRowSorter(true);
      tblPeople.setForeground(new java.awt.Color(51, 51, 51));
      tblPeople.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
         },
         new String [] {
            "IC No", "Name", "Password", "Contact No", "Malaysian"
         }
      ) {
         boolean[] canEdit = new boolean [] {
            false, false, false, false, false
         };

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tblPeople.setSelectionBackground(new java.awt.Color(153, 153, 255));
      tblPeople.setSelectionForeground(new java.awt.Color(51, 51, 51));
      tblPeople.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      tblPeople.getTableHeader().setReorderingAllowed(false);
      tblPeople.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblPeopleMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblPeople);
      if (tblPeople.getColumnModel().getColumnCount() > 0) {
         tblPeople.getColumnModel().getColumn(2).setCellRenderer(null);
      }

      btnRefresh.setText("Refresh");
      btnRefresh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
         }
      });

      jLabel6.setText("Contact No :");

      chkCitizen.setText("Citizen of Malaysia");

      jLabel3.setText("Name :");

      jLabel4.setText("Password :");

      jLabel5.setText("IC No :");

      btnRegister.setText("Register");

      btnUpdate.setText("Update");

      btnClear.setText("Clear");
      btnClear.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClearActionPerformed(evt);
         }
      });

      btnDelete.setText("Delete");

      jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jLabel7.setText("Manage People Profiles");
      jLabel7.setToolTipText("");
      jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      chkPassword.setText("Show Password");
      chkPassword.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chkPasswordActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addGap(151, 151, 151)
                  .addComponent(jLabel7)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addGap(57, 57, 57)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addGap(5, 5, 5)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                 .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(chkPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addComponent(txtName)
                                 .addComponent(txtIC)
                                 .addComponent(txtContact)))
                           .addComponent(chkCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGap(60, 60, 60))
         .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(24, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4)
               .addComponent(chkPassword))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(chkCitizen)
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(btnDelete)
               .addComponent(btnClear)
               .addComponent(btnUpdate)
               .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnRefresh))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12))
      );

      layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClear, btnDelete, btnRegister, btnUpdate});

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void tblPeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeopleMouseClicked

      txtIC.setText(tblPeople.getValueAt(tblPeople.getSelectedRow(), 0).toString());
      txtName.setText(tblPeople.getValueAt(tblPeople.getSelectedRow(), 1).toString());
      txtPassword.setText(tblPeople.getValueAt(tblPeople.getSelectedRow(), 2).toString());
      txtContact.setText(tblPeople.getValueAt(tblPeople.getSelectedRow(), 3).toString());
      chkCitizen.setSelected(Boolean.valueOf(tblPeople.getValueAt(tblPeople.getSelectedRow(), 4).toString()));
   }//GEN-LAST:event_tblPeopleMouseClicked

   private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
      if (chkPassword.isSelected()) {
         txtPassword.setEchoChar((char) 0); //password = JPasswordField
      } else {
         txtPassword.setEchoChar('*');
      }
   }//GEN-LAST:event_chkPasswordActionPerformed

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

      DefaultTableModel model = (DefaultTableModel) tblPeople.getModel();
      model.setRowCount(0);
      for (int i = 0; i < DataIO.allPeople.size(); i++) {
         String icno = DataIO.allPeople.get(i).getIcno();
         String name = DataIO.allPeople.get(i).getName();
         String password = DataIO.allPeople.get(i).getPassword();
         String contact = DataIO.allPeople.get(i).getPhone();
         String citizen = String.valueOf(DataIO.allPeople.get(i).isCitizen());
         String array[] = {icno, name, password, contact, citizen};
         model.addRow(array);
      }
      tblPeople.getColumnModel().getColumn(2).setMinWidth(0);
      tblPeople.getColumnModel().getColumn(2).setMaxWidth(0);
      btnClearActionPerformed(evt);
   }//GEN-LAST:event_btnRefreshActionPerformed

   private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
      txtIC.setText("");
      txtName.setText("");
      txtPassword.setText("");
      txtContact.setText("");
      txtSearch.setText("");
      chkCitizen.setSelected(false);
      chkPassword.setSelected(false);
   }//GEN-LAST:event_btnClearActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdminPeopleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdminPeopleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdminPeopleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdminPeopleManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new AdminPeopleManagement().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClear;
   private javax.swing.JButton btnDelete;
   private javax.swing.JButton btnRefresh;
   private javax.swing.JButton btnRegister;
   private javax.swing.JButton btnUpdate;
   private javax.swing.JCheckBox chkCitizen;
   private javax.swing.JCheckBox chkPassword;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblPeople;
   private javax.swing.JTextField txtContact;
   private javax.swing.JTextField txtIC;
   private javax.swing.JTextField txtName;
   private javax.swing.JPasswordField txtPassword;
   private javax.swing.JTextField txtSearch;
   // End of variables declaration//GEN-END:variables
}
